#!/usr/bin/env python3
"""
Northwind Cloud — step 8: generate the data dictionary and the cleaning-rules
document straight from the warehouse, so they cannot drift from the code.
"""
from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "data" / "warehouse" / "northwind.db"
DOCS = ROOT / "docs"

COLUMN_NOTES = {
    ("fact_subscription_month", "movement_type"):
        "opening_balance | new | expansion | contraction | churn | reactivation | flat. "
        "Derived from month-over-month MRR, never copied from the source system.",
    ("fact_subscription_month", "movement_amount"):
        "Signed. Contraction and churn are negative, which is what makes the bridge foot.",
    ("fact_subscription_month", "prev_mrr"):
        "Prior month's MRR for the same customer; 0 in the first month.",
    ("fact_subscription_month", "outlier_flag"):
        "1 = movement beyond 5 sigma. Flagged, never removed or normalised.",
    ("dim_customer", "is_pre_window"):
        "1 = acquired before the S&M ledger begins. EXCLUDE from all CAC and payback.",
    ("dim_customer", "segment_imputed"):
        "1 = segment was missing and imputed from first-month ARR bands (rule R06).",
    ("dim_customer", "channel_unattributed"):
        "1 = acquisition channel was missing. Never imputed; bucketed as 'unattributed'.",
    ("dim_customer", "first_month_arr"):
        "Entry ACV: first billed MRR x 12. The correct denominator for payback.",
    ("dim_channel", "sales_touch_weight"):
        "Relative AE/SE effort one won deal consumes. Basis for allocating shared sales cost.",
    ("dim_segment", "sales_effort_index"):
        "Stated judgement, not an observation. Alternative CAC allocation basis in Q09.",
    ("fact_credit_memo", "credit_amount"):
        "Negative. Reduces recognised revenue; deliberately NOT netted into MRR.",
    ("fact_marketing_spend", "leads"):
        "Raw leads for spend-driven channels; booked MEETINGS for outbound_sdr, "
        "whose volume comes from rep capacity rather than spend.",
    ("dim_date", "is_actual"):
        "1 = one of the 36 actual months; 0 = one of the 18 forecast months.",
}


def main() -> int:
    con = sqlite3.connect(DB)
    DOCS.mkdir(exist_ok=True)

    # ---------------------------------------------------- cleaning rules ----
    au = pd.read_sql("SELECT * FROM etl_audit ORDER BY step_no", con)
    qn = pd.read_sql("SELECT rule_id, COUNT(*) n, MIN(reason) reason "
                     "FROM dq_quarantine GROUP BY rule_id", con).set_index("rule_id")
    lines = [
        "# Cleaning rules and ETL audit",
        "",
        "Generated by `src/08_generate_docs.py` from the `etl_audit` table, so it",
        "cannot drift from what the code actually does. Rules run in order; every",
        "one records rows in, rows out and rows affected. Nothing is dropped without",
        "a row in `dq_quarantine` carrying the original record and a reason.",
        "",
        "## Three decisions worth arguing with",
        "",
        "**Credit memos are not netted into MRR.** MRR measures the recurring",
        "contract. A one-off, back-dated credit is not a change to that contract.",
        "They live in `fact_credit_memo` and reduce *recognised revenue*, which is",
        "what the cash model consumes. Conflating the two is the most common reason",
        "a SaaS ARR bridge stops tying.",
        "",
        "**Missing acquisition channel is never imputed.** Attribution cannot be",
        f"reconstructed from revenue. Guessing would feed a fabricated denominator",
        "straight into CAC. Those customers go to an explicit `unattributed` bucket",
        "and are excluded from every channel CAC figure.",
        "",
        "**Outliers are flagged, not normalised.** The only outlier treatment applied",
        "anywhere is R05, and only because it has a documented mechanical cause: the",
        "February 2026 billing-engine cut-over double-posted invoices. Every other",
        "extreme movement stays in the history with `outlier_flag = 1`. Removing",
        "unexplained outliers is curve-fitting.",
        "",
        "## Rules",
        "",
        "| # | Rule | Table | Rows in | Rows out | Affected | Quarantined | Severity |",
        "|---:|---|---|---:|---:|---:|---:|---|",
    ]
    for _, r in au.iterrows():
        q = int(qn.n.get(r.rule_id, 0))
        lines.append(f"| {r.step_no} | **{r.rule_id}** {r.rule_name} | `{r.table_name}` | "
                     f"{r.rows_in:,} | {r.rows_out:,} | {r.rows_affected:,} | "
                     f"{q:,} | {r.severity} |")
    lines += ["", "## Rule detail", ""]
    for _, r in au.iterrows():
        lines.append(f"### {r.rule_id} — {r.rule_name}")
        lines.append("")
        lines.append(r.rule_description)
        if r.rule_id in qn.index:
            lines.append("")
            lines.append(f"Quarantined {int(qn.n[r.rule_id]):,} rows. "
                         f"Reason recorded: _{qn.reason[r.rule_id]}_")
        lines.append("")
    (DOCS / "CLEANING_RULES.md").write_text("\n".join(lines) + "\n")

    # ---------------------------------------------------- data dictionary ---
    objs = pd.read_sql(
        "SELECT name, type FROM sqlite_master WHERE type IN ('table','view') "
        "AND name NOT LIKE 'sqlite_%' ORDER BY type DESC, name", con)
    out = [
        "# Data dictionary — `data/warehouse/northwind.db`",
        "",
        "Generated by `src/08_generate_docs.py`. Star schema: `dim_*` dimensions,",
        "`fact_*` facts, `ref_*` reference, plus the ETL audit tables and three",
        "analysis views the SQL library reads from.",
        "",
        "**Grain of `fact_subscription_month` is customer x month.** It is a dense",
        "spine: each customer has a contiguous run of months from first to last",
        "active month plus one trailing month, so churn is an observable event",
        "rather than a missing row.",
        "",
    ]
    for _, o in objs.iterrows():
        n = int(pd.read_sql(f"SELECT COUNT(*) c FROM {o['name']}", con).c.iloc[0])
        cols = pd.read_sql(f"PRAGMA table_info({o['name']})", con)
        out.append(f"## `{o['name']}` — {o['type']}, {n:,} rows")
        out.append("")
        out.append("| Column | Type | Note |")
        out.append("|---|---|---|")
        for _, c in cols.iterrows():
            note = COLUMN_NOTES.get((o["name"], c["name"]), "")
            out.append(f"| `{c['name']}` | {c['type'] or 'ANY'} | {note} |")
        out.append("")
    (DOCS / "DATA_DICTIONARY.md").write_text("\n".join(out) + "\n")

    con.close()
    print("wrote docs/CLEANING_RULES.md and docs/DATA_DICTIONARY.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
